services:

    pergunta_model:
        class: Fish\Bundle\Model\PerguntaModel
        arguments: ['@service_container']
    resposta_model:
        class: Fish\Bundle\Model\RespostaModel
        arguments: ['@service_container']

    pergunta_entity:
        scope: prototype
        class: Fish\Bundle\Entity\PerguntaEntity
    resposta_entity:
        scope: prototype
        class: Fish\Bundle\Entity\RespostaEntity