Fish\Bundle\Entity\EnqueteEntity:
    type: entity
    schema: enquete
    table: enquete
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        titulo:
            type: string
            length: 255
    oneToMany:
        perguntas:
            targetEntity: Fish\Bundle\Entity\PerguntaEntity
            mappedBy: enquete
            cascade: ['persist']