Fish\Bundle\Entity\PerguntaEntity:
    type: entity
    schema: enquete
    table: pergunta
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        pergunta:
            type: string
            length: 255
    manyToOne:
        enquete:
            targetEntity: Fish\Bundle\Entity\EnqueteEntity
            cascade: ['persist']
            joinColumn:
                name: enquete_id
                referencedColumnName: id
    oneToMany:
        respostas:
            targetEntity: Fish\Bundle\Entity\RespostaEntity
            mappedBy: pergunta
            cascade: ['persist']