Fish\Bundle\Entity\RespostaEntity:
    type: entity
    schema: enquete
    table: resposta
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        resposta:
            type: string
            length: 255
        quantidadeVotos:
            column: quantidade_votos
            type: integer
            default: 0
    manyToOne:
        pergunta:
            targetEntity: Fish\Bundle\Entity\PerguntaEntity
            joinColumn:
                name: pergunta_id
                referencedColumnName: id